name: Discord
on:
  push:
    branches:
      - main
jobs:
  discord:
    name: notification
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Run Discord Webhook
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}