name: Discord
on:
<<<<<<< HEAD
  - push

=======
  push:
    branches:
      - main
>>>>>>> 6a02611515fdde60b7626b736d38554b63151571
jobs:
  discord:
    name: notification
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Run Discord Webhook
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true